import express from 'express';import http from 'http';import { Server } from 'socket.io';import path from 'path';import { fileURLToPath } from 'url';const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);
const app=express(),server=http.createServer(app),io=new Server(server),rooms=new Map();app.use(express.static(path.join(__dirname,'public')));
const makeCode=()=>Math.random().toString(36).slice(2,7).toUpperCase();
function newRoom(max,host){return{host,max,status:'lobby',round:0,roundSize:12,players:[host],answers:{},history:[],startedAt:null};}
function publicRoom(r){return{host:r.host.id,max:r.max,status:r.status,round:r.round,players:r.players.map(p=>({id:p.id,name:p.name,gender:p.gender,score:p.score||0,answered:!!r.answers[p.id]}))};}
io.on('connection',socket=>{
 socket.on('createRoom',({name,max=8,gender='unspecified'},cb)=>{max=Math.max(2,Math.min(8,Number(max)||8));let code=makeCode();while(rooms.has(code))code=makeCode();const p={id:socket.id,name:String(name||'Player').slice(0,40),gender,score:0};const r=newRoom(max,p);rooms.set(code,r);socket.join(code);cb({ok:true,room:code});io.to(code).emit('room',publicRoom(r));});
 socket.on('joinRoom',({room,name,gender='unspecified'},cb)=>{const code=String(room||'').toUpperCase(),r=rooms.get(code);if(!r)return cb({ok:false,error:'Room not found.'});if(r.status!=='lobby')return cb({ok:false,error:'This room has already started.'});if(r.players.length>=r.max)return cb({ok:false,error:'Room is full.'});const p={id:socket.id,name:String(name||'Player').slice(0,40),gender,score:0};r.players.push(p);socket.join(code);cb({ok:true,room:code});io.to(code).emit('room',publicRoom(r));});
 socket.on('start',code=>{const r=rooms.get(code);if(!r||r.host.id!==socket.id||r.players.length<2)return;r.status='playing';r.round=0;r.answers={};r.startedAt=Date.now();io.to(code).emit('start',{round:0,total:12,roundSize:r.roundSize});io.to(code).emit('room',publicRoom(r));});
 socket.on('answer',({room,answer,metadata={}})=>{const r=rooms.get(room);if(!r||r.status!=='playing'||r.answers[socket.id])return;r.answers[socket.id]={answer,metadata,at:Date.now()};io.to(room).emit('room',publicRoom(r));if(r.players.every(p=>r.answers[p.id])){r.players.forEach(p=>{const a=r.answers[p.id];p.score=(p.score||0)+(Number(a.metadata?.points)||0)});r.history.push({round:r.round,answers:r.answers});r.status='round-complete';io.to(room).emit('roundComplete',{round:r.round,scores:r.players.map(p=>({id:p.id,name:p.name,score:p.score}))});}});
 socket.on('continueRound',({room})=>{const r=rooms.get(room);if(!r||r.status!=='round-complete'||r.host.id!==socket.id)return;r.round++;r.answers={};if(r.round>=4){r.status='complete';io.to(room).emit('complete',{rounds:r.history,scores:r.players.map(p=>({id:p.id,name:p.name,score:p.score}))});return;}r.status='playing';io.to(room).emit('next',{round:r.round});io.to(room).emit('room',publicRoom(r));});
 socket.on('endRoom',({room})=>{const r=rooms.get(room);if(!r||r.host.id!==socket.id)return;r.status='complete';io.to(room).emit('complete',{rounds:r.history,scores:r.players.map(p=>({id:p.id,name:p.name,score:p.score}))});});
 socket.on('disconnect',()=>{for(const[code,r]of rooms){const i=r.players.findIndex(p=>p.id===socket.id);if(i<0)continue;if(r.host.id===socket.id){rooms.delete(code);io.to(code).emit('closed');}else{r.players.splice(i,1);io.to(code).emit('room',publicRoom(r));}}});
});
const port=process.env.PORT||3000;server.listen(port,()=>console.log('Eve U Wan Adam Add Am Core Engine v3 listening on '+port));
